/* Generated By:JavaCC: Do not edit this line. MarkusLangParserConstants.java */
package markuslang.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MarkusLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIABLE = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int STRING = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "<token of kind 5>",
    "\"i am the dictator\"",
    "\"everything is peachy\"",
    "\"this little piggy\"",
    "\"is\"",
    "\"what is this thingy\"",
    "\"?\"",
    "<VARIABLE>",
    "<NUMBER>",
    "<STRING>",
  };

}
